version: 0.2

phases:
  install:
    run-as: root
    commands:
      - cd cfn
      - ls
  build:
    run-as: root
    commands:
      - 
artifacts:
  files:
    - '**/*'
  base-directory: 'release'
